import { createContext, createElement, useContext, useEffect, useMemo, useState } from 'react';

export const LOCALES = [
  { code: 'en', label: 'English' },
  { code: 'id', label: 'Bahasa Indonesia' },
  { code: 'ms', label: 'Bahasa Melayu' },
];

const COPY = {
  en: {
    'a11y.skip': 'Skip to content', 'a11y.home': 'PA DEV STUDIO home', 'a11y.primary': 'Primary navigation', 'media.hero': 'PA DEV dashboard shown on laptop and mobile devices', 'media.preview': 'interface preview', 'media.caseStudy': 'case study interface', 'media.article': 'article illustration', 'media.process': 'process illustration',
    'a11y.mobile': 'Mobile navigation', 'a11y.openMenu': 'Open menu', 'a11y.closeMenu': 'Close menu',
    'a11y.switchLight': 'Switch to light theme', 'a11y.switchDark': 'Switch to dark theme',
    'publicLogin.title': 'Public Login', 'publicLogin.subtitle': 'Sign in to your PA DEV Studio public account.', 'publicLogin.email': 'Email address', 'publicLogin.password': 'Password', 'publicLogin.submit': 'Continue', 'publicLogin.back': 'Back to website', 'publicLogin.pending': 'Public accounts are not active yet. This screen is ready for the next roadmap phase.', 'publicAuth.eyebrow': 'Public account', 'publicAuth.loginTitle': 'Welcome back', 'publicAuth.loginSubtitle': 'Sign in to continue from the PA DEV Studio website.', 'publicAuth.registerTitle': 'Create your account', 'publicAuth.registerSubtitle': 'Register once to keep your public profile and future projects in one place.', 'publicAuth.name': 'Full name', 'publicAuth.email': 'Email address', 'publicAuth.password': 'Password', 'publicAuth.passwordConfirmation': 'Confirm password', 'publicAuth.google': 'Continue with Google', 'publicAuth.github': 'Continue with GitHub', 'publicAuth.or': 'or continue with email', 'publicAuth.login': 'Log in', 'publicAuth.register': 'Register', 'publicAuth.processing': 'Processing…', 'publicAuth.failed': 'We could not complete that request. Please try again.', 'publicAuth.noAccount': "Don't have an account?", 'publicAuth.haveAccount': 'Already have an account?', 'publicAuth.profile': 'My profile', 'publicAuth.settings': 'Settings', 'publicAuth.logout': 'Log out', 'publicAuth.accountPending': 'The public account area is being prepared.', 'language.label': 'Language', 'nav.home': 'Home', 'nav.services': 'Services', 'nav.projects': 'Projects', 'nav.templates': 'Templates',
    'nav.insights': 'Insights', 'nav.about': 'About', 'nav.contact': 'Contact', 'nav.menu': 'Menu', 'cta.publicLogin': 'Login',
    'hero.benefit.clean': 'Clean Code · Scalable', 'hero.benefit.performance': 'Performance · Optimized', 'hero.benefit.secure': 'Secure · Reliable', 'hero.benefit.delivery': 'On-Time · Delivery',
    'stats.years': 'Years Experience', 'stats.projects': 'Projects Completed', 'stats.clients': 'Happy Clients', 'stats.satisfaction': 'Client Satisfaction',
    'services.eyebrow': 'Services', 'services.title': 'End-to-End Digital Solutions.', 'services.text': 'From strategy and design to development and deployment, I deliver reliable solutions that drive growth.', 'services.all': 'View all services',
    'templates.eyebrow': 'Templates Marketplace', 'templates.title': 'Launch faster with premium templates.', 'templates.all': 'View all templates', 'templates.filter': 'Filter templates', 'templates.allFilter': 'All', 'templates.details': 'View Details',
    'projects.eyebrow': 'Featured Case Studies', 'projects.title': 'Real projects. Real impact.', 'projects.all': 'View all projects', 'projects.case': 'View Case Study',
    'tech.eyebrow': 'Tech Stack', 'tech.title': 'Modern technologies for modern solutions.', 'process.eyebrow': 'My Process', 'process.title': 'A clear process for great results.', 'process.all': 'View how it works', 'process.discover.title': 'Discover', 'process.discover.text': 'Understand your goals & requirements.', 'process.plan.title': 'Plan', 'process.plan.text': 'Research, architecture & project roadmap.', 'process.design.title': 'Design', 'process.design.text': 'UI/UX design & prototyping.', 'process.develop.title': 'Develop', 'process.develop.text': 'Build, test & implement clean code.', 'process.deploy.title': 'Deploy', 'process.deploy.text': 'Launch, monitor & optimise.', 'process.support.title': 'Support', 'process.support.text': 'Ongoing support & improvements.', 'profile.title': 'Full-Stack Developer &', 'profile.subtitle': 'Digital Problem Solver', 'profile.alt': 'Anime portrait of Pradita Alfiantoni, Full-Stack Developer and Digital Problem Solver',
    'proof.eyebrow': 'What Clients Say', 'pricing.eyebrow': 'Pricing Plans', 'pricing.popular': 'Most Popular', 'insights.eyebrow': 'Latest Insights', 'insights.all': 'View all articles', 'insights.read': '5 min read',
    'faq.eyebrow': 'FAQ', 'faq.title': "Questions? We've got answers.", 'newsletter.eyebrow': 'Stay Updated', 'newsletter.title': 'Get tips, insights, and resources straight to your inbox.', 'newsletter.text': 'Join 500+ developers and business owners.', 'newsletter.email': 'Email address', 'newsletter.placeholder': 'Enter your email address', 'newsletter.send': 'Sending…', 'newsletter.subscribe': 'Subscribe', 'newsletter.note': 'No spam. Unsubscribe anytime.', 'newsletter.invalid': 'Please enter a valid email address.', 'newsletter.failed': 'Subscription failed. Please try again.', 'newsletter.thanks': 'Thanks — you are on the list!',
    'contact.eyebrow': "Let's Work Together", 'contact.title': 'Have a project in mind?', 'contact.text': "Let's build something amazing together.", 'contact.email': 'Email', 'contact.phone': 'Phone / WhatsApp', 'contact.location': 'Location', 'contact.availability': 'Availability', 'contact.name': 'Your Name', 'contact.emailAddress': 'Email Address', 'contact.service': 'Service', 'contact.selectService': 'Select Service', 'contact.detail': 'Project Detail', 'contact.detailPlaceholder': 'Tell me about your project…', 'contact.send': 'Send Message', 'contact.invalid': 'Please complete your name and a valid email address.', 'contact.failed': 'Message could not be sent. Please try again.', 'contact.thanks': 'Thank you. Your message has been received.',
    'footer.company': 'Company', 'footer.resources': 'Resources', 'footer.privacy': 'Privacy Policy', 'footer.terms': 'Terms of Service', 'footer.about': 'About Me', 'footer.process': 'My Process', 'footer.case': 'Case Studies', 'footer.testimonials': 'Testimonials', 'footer.pricing': 'Pricing', 'footer.blog': 'Blog & Insights', 'footer.guides': 'Guides', 'footer.changelog': 'Changelog', 'footer.rights': 'All rights reserved.',
  },
  id: {
    'a11y.skip': 'Lewati ke konten', 'a11y.home': 'Beranda PA DEV STUDIO', 'a11y.primary': 'Navigasi utama', 'a11y.mobile': 'Navigasi seluler', 'a11y.openMenu': 'Buka menu', 'a11y.closeMenu': 'Tutup menu', 'a11y.switchLight': 'Ganti ke tema terang', 'a11y.switchDark': 'Ganti ke tema gelap', 'media.hero': 'Dashboard PA DEV di laptop dan perangkat seluler', 'media.preview': 'pratinjau antarmuka', 'media.caseStudy': 'antarmuka studi kasus', 'media.article': 'ilustrasi artikel', 'media.process': 'ilustrasi proses',
    'publicLogin.title': 'Login', 'publicLogin.subtitle': 'Masuk ke akun publik PA DEV Studio Anda.', 'publicLogin.email': 'Alamat email', 'publicLogin.password': 'Kata sandi', 'publicLogin.submit': 'Lanjutkan', 'publicLogin.back': 'Kembali ke website', 'publicLogin.pending': 'Akun publik belum diaktifkan. Halaman ini sudah disiapkan untuk fase roadmap berikutnya.', 'publicAuth.eyebrow': 'Akun publik', 'publicAuth.loginTitle': 'Selamat datang kembali', 'publicAuth.loginSubtitle': 'Masuk untuk melanjutkan dari website PA DEV Studio.', 'publicAuth.registerTitle': 'Buat akun Anda', 'publicAuth.registerSubtitle': 'Daftar sekali untuk menyimpan profil publik dan proyek Anda di masa depan.', 'publicAuth.name': 'Nama lengkap', 'publicAuth.email': 'Alamat email', 'publicAuth.password': 'Kata sandi', 'publicAuth.passwordConfirmation': 'Konfirmasi kata sandi', 'publicAuth.google': 'Lanjutkan dengan Google', 'publicAuth.github': 'Lanjutkan dengan GitHub', 'publicAuth.or': 'atau lanjutkan dengan email', 'publicAuth.login': 'Login', 'publicAuth.register': 'Register', 'publicAuth.processing': 'Memproses…', 'publicAuth.failed': 'Permintaan belum berhasil. Silakan coba lagi.', 'publicAuth.noAccount': 'Belum punya akun?', 'publicAuth.haveAccount': 'Sudah punya akun?', 'publicAuth.profile': 'Profil Saya', 'publicAuth.settings': 'Settings', 'publicAuth.logout': 'Logout', 'publicAuth.accountPending': 'Area akun publik sedang disiapkan.', 'language.label': 'Bahasa', 'nav.home': 'Beranda', 'nav.services': 'Layanan', 'nav.projects': 'Proyek', 'nav.templates': 'Template', 'nav.insights': 'Wawasan', 'nav.about': 'Tentang', 'nav.contact': 'Kontak', 'nav.menu': 'Menu', 'cta.publicLogin': 'Login',
    'hero.benefit.clean': 'Kode Bersih · Skalabel', 'hero.benefit.performance': 'Performa · Optimal', 'hero.benefit.secure': 'Aman · Andal', 'hero.benefit.delivery': 'Tepat Waktu · Tuntas', 'stats.years': 'Tahun Pengalaman', 'stats.projects': 'Proyek Selesai', 'stats.clients': 'Klien Puas', 'stats.satisfaction': 'Kepuasan Klien',
    'services.eyebrow': 'Layanan', 'services.title': 'Solusi Digital Menyeluruh.', 'services.text': 'Dari strategi dan desain hingga pengembangan dan peluncuran, saya menghadirkan solusi andal yang mendorong pertumbuhan.', 'services.all': 'Lihat semua layanan', 'templates.eyebrow': 'Marketplace Template', 'templates.title': 'Luncurkan lebih cepat dengan template premium.', 'templates.all': 'Lihat semua template', 'templates.filter': 'Saring template', 'templates.allFilter': 'Semua', 'templates.details': 'Lihat Detail', 'projects.eyebrow': 'Studi Kasus Pilihan', 'projects.title': 'Proyek nyata. Dampak nyata.', 'projects.all': 'Lihat semua proyek', 'projects.case': 'Lihat Studi Kasus', 'tech.eyebrow': 'Teknologi', 'tech.title': 'Teknologi modern untuk solusi modern.', 'process.eyebrow': 'Proses Saya', 'process.title': 'Proses jelas untuk hasil terbaik.', 'process.all': 'Lihat cara kerjanya', 'process.discover.title': 'Temukan', 'process.discover.text': 'Pahami tujuan dan kebutuhan Anda.', 'process.plan.title': 'Rencanakan', 'process.plan.text': 'Riset, arsitektur, dan peta jalan proyek.', 'process.design.title': 'Rancang', 'process.design.text': 'Desain UI/UX dan pembuatan prototipe.', 'process.develop.title': 'Kembangkan', 'process.develop.text': 'Bangun, uji, dan terapkan kode yang bersih.', 'process.deploy.title': 'Luncurkan', 'process.deploy.text': 'Rilis, pantau, dan optimalkan.', 'process.support.title': 'Dukung', 'process.support.text': 'Dukungan dan peningkatan berkelanjutan.', 'profile.title': 'Pengembang Full-Stack &', 'profile.subtitle': 'Pemecah Masalah Digital', 'profile.alt': 'Potret anime Pradita Alfiantoni, Pengembang Full-Stack dan Pemecah Masalah Digital', 'proof.eyebrow': 'Kata Klien', 'pricing.eyebrow': 'Paket Harga', 'pricing.popular': 'Paling Populer', 'insights.eyebrow': 'Wawasan Terbaru', 'insights.all': 'Lihat semua artikel', 'insights.read': 'Baca 5 menit',
    'faq.eyebrow': 'FAQ', 'faq.title': 'Punya pertanyaan? Kami punya jawabannya.', 'newsletter.eyebrow': 'Tetap Terhubung', 'newsletter.title': 'Dapatkan tips, wawasan, dan sumber daya langsung ke kotak masuk Anda.', 'newsletter.text': 'Bergabung dengan 500+ pengembang dan pemilik bisnis.', 'newsletter.email': 'Alamat email', 'newsletter.placeholder': 'Masukkan alamat email', 'newsletter.send': 'Mengirim…', 'newsletter.subscribe': 'Berlangganan', 'newsletter.note': 'Tanpa spam. Berhenti kapan saja.', 'newsletter.invalid': 'Masukkan alamat email yang valid.', 'newsletter.failed': 'Langganan gagal. Silakan coba lagi.', 'newsletter.thanks': 'Terima kasih — Anda sudah masuk daftar!',
    'contact.eyebrow': 'Mari Bekerja Sama', 'contact.title': 'Punya proyek dalam pikiran?', 'contact.text': 'Mari membangun sesuatu yang luar biasa bersama.', 'contact.email': 'Email', 'contact.phone': 'Telepon / WhatsApp', 'contact.location': 'Lokasi', 'contact.availability': 'Ketersediaan', 'contact.name': 'Nama Anda', 'contact.emailAddress': 'Alamat Email', 'contact.service': 'Layanan', 'contact.selectService': 'Pilih Layanan', 'contact.detail': 'Detail Proyek', 'contact.detailPlaceholder': 'Ceritakan proyek Anda…', 'contact.send': 'Kirim Pesan', 'contact.invalid': 'Lengkapi nama dan alamat email yang valid.', 'contact.failed': 'Pesan gagal dikirim. Silakan coba lagi.', 'contact.thanks': 'Terima kasih. Pesan Anda sudah diterima.',
    'footer.company': 'Perusahaan', 'footer.resources': 'Sumber Daya', 'footer.privacy': 'Kebijakan Privasi', 'footer.terms': 'Ketentuan Layanan', 'footer.about': 'Tentang Saya', 'footer.process': 'Proses Saya', 'footer.case': 'Studi Kasus', 'footer.testimonials': 'Testimoni', 'footer.pricing': 'Harga', 'footer.blog': 'Blog & Wawasan', 'footer.guides': 'Panduan', 'footer.changelog': 'Catatan Perubahan', 'footer.rights': 'Hak cipta dilindungi.',
  },
  ms: {
    'a11y.skip': 'Langkau ke kandungan', 'a11y.home': 'Laman utama PA DEV STUDIO', 'a11y.primary': 'Navigasi utama', 'a11y.mobile': 'Navigasi mudah alih', 'a11y.openMenu': 'Buka menu', 'a11y.closeMenu': 'Tutup menu', 'a11y.switchLight': 'Tukar kepada tema cerah', 'a11y.switchDark': 'Tukar kepada tema gelap', 'media.hero': 'Papan pemuka PA DEV pada komputer riba dan peranti mudah alih', 'media.preview': 'pratonton antara muka', 'media.caseStudy': 'antara muka kajian kes', 'media.article': 'ilustrasi artikel', 'media.process': 'ilustrasi proses',
    'publicLogin.title': 'Log Masuk', 'publicLogin.subtitle': 'Log masuk ke akaun awam PA DEV Studio anda.', 'publicLogin.email': 'Alamat emel', 'publicLogin.password': 'Kata laluan', 'publicLogin.submit': 'Teruskan', 'publicLogin.back': 'Kembali ke laman web', 'publicLogin.pending': 'Akaun awam belum diaktifkan. Skrin ini disediakan untuk fasa roadmap seterusnya.', 'publicAuth.eyebrow': 'Akaun awam', 'publicAuth.loginTitle': 'Selamat kembali', 'publicAuth.loginSubtitle': 'Log masuk untuk meneruskan dari laman web PA DEV Studio.', 'publicAuth.registerTitle': 'Cipta akaun anda', 'publicAuth.registerSubtitle': 'Daftar sekali untuk menyimpan profil awam dan projek masa depan anda.', 'publicAuth.name': 'Nama penuh', 'publicAuth.email': 'Alamat emel', 'publicAuth.password': 'Kata laluan', 'publicAuth.passwordConfirmation': 'Sahkan kata laluan', 'publicAuth.google': 'Teruskan dengan Google', 'publicAuth.github': 'Teruskan dengan GitHub', 'publicAuth.or': 'atau teruskan dengan emel', 'publicAuth.login': 'Log masuk', 'publicAuth.register': 'Daftar', 'publicAuth.processing': 'Memproses…', 'publicAuth.failed': 'Permintaan tidak berjaya. Sila cuba lagi.', 'publicAuth.noAccount': 'Belum ada akaun?', 'publicAuth.haveAccount': 'Sudah ada akaun?', 'publicAuth.profile': 'Profil Saya', 'publicAuth.settings': 'Tetapan', 'publicAuth.logout': 'Log keluar', 'publicAuth.accountPending': 'Ruang akaun awam sedang disediakan.', 'language.label': 'Bahasa', 'nav.home': 'Laman Utama', 'nav.services': 'Perkhidmatan', 'nav.projects': 'Projek', 'nav.templates': 'Templat', 'nav.insights': 'Pandangan', 'nav.about': 'Tentang', 'nav.contact': 'Hubungi', 'nav.menu': 'Menu', 'cta.publicLogin': 'Log Masuk',
    'hero.benefit.clean': 'Kod Bersih · Boleh Skala', 'hero.benefit.performance': 'Prestasi · Optimum', 'hero.benefit.secure': 'Selamat · Dipercayai', 'hero.benefit.delivery': 'Tepat Masa · Selesai', 'stats.years': 'Tahun Pengalaman', 'stats.projects': 'Projek Selesai', 'stats.clients': 'Pelanggan Berpuas Hati', 'stats.satisfaction': 'Kepuasan Pelanggan',
    'services.eyebrow': 'Perkhidmatan', 'services.title': 'Penyelesaian Digital Menyeluruh.', 'services.text': 'Daripada strategi dan reka bentuk hingga pembangunan dan pelancaran, saya menyediakan penyelesaian yang memacu pertumbuhan.', 'services.all': 'Lihat semua perkhidmatan', 'templates.eyebrow': 'Pasaran Templat', 'templates.title': 'Lancarkan lebih pantas dengan templat premium.', 'templates.all': 'Lihat semua templat', 'templates.filter': 'Tapis templat', 'templates.allFilter': 'Semua', 'templates.details': 'Lihat Butiran', 'projects.eyebrow': 'Kajian Kes Pilihan', 'projects.title': 'Projek sebenar. Impak sebenar.', 'projects.all': 'Lihat semua projek', 'projects.case': 'Lihat Kajian Kes', 'tech.eyebrow': 'Teknologi', 'tech.title': 'Teknologi moden untuk penyelesaian moden.', 'process.eyebrow': 'Proses Saya', 'process.title': 'Proses jelas untuk hasil hebat.', 'process.all': 'Lihat caranya', 'process.discover.title': 'Temui', 'process.discover.text': 'Fahami matlamat dan keperluan anda.', 'process.plan.title': 'Rancang', 'process.plan.text': 'Penyelidikan, seni bina dan peta jalan projek.', 'process.design.title': 'Reka Bentuk', 'process.design.text': 'Reka bentuk UI/UX dan prototaip.', 'process.develop.title': 'Bangunkan', 'process.develop.text': 'Bina, uji dan laksanakan kod bersih.', 'process.deploy.title': 'Lancarkan', 'process.deploy.text': 'Lancarkan, pantau dan optimumkan.', 'process.support.title': 'Sokong', 'process.support.text': 'Sokongan dan penambahbaikan berterusan.', 'profile.title': 'Pembangun Full-Stack &', 'profile.subtitle': 'Penyelesai Masalah Digital', 'profile.alt': 'Potret anime Pradita Alfiantoni, Pembangun Full-Stack dan Penyelesai Masalah Digital', 'proof.eyebrow': 'Kata Pelanggan', 'pricing.eyebrow': 'Pelan Harga', 'pricing.popular': 'Paling Popular', 'insights.eyebrow': 'Pandangan Terkini', 'insights.all': 'Lihat semua artikel', 'insights.read': 'Baca 5 minit',
    'faq.eyebrow': 'FAQ', 'faq.title': 'Ada soalan? Kami ada jawapan.', 'newsletter.eyebrow': 'Kekal Dikemas Kini', 'newsletter.title': 'Dapatkan tip, pandangan dan sumber terus ke peti masuk anda.', 'newsletter.text': 'Sertai 500+ pembangun dan pemilik perniagaan.', 'newsletter.email': 'Alamat emel', 'newsletter.placeholder': 'Masukkan alamat emel', 'newsletter.send': 'Menghantar…', 'newsletter.subscribe': 'Langgan', 'newsletter.note': 'Tiada spam. Berhenti bila-bila masa.', 'newsletter.invalid': 'Sila masukkan alamat emel yang sah.', 'newsletter.failed': 'Langganan gagal. Sila cuba lagi.', 'newsletter.thanks': 'Terima kasih — anda sudah tersenarai!',
    'contact.eyebrow': 'Mari Bekerjasama', 'contact.title': 'Ada projek dalam fikiran?', 'contact.text': 'Mari bina sesuatu yang hebat bersama.', 'contact.email': 'Emel', 'contact.phone': 'Telefon / WhatsApp', 'contact.location': 'Lokasi', 'contact.availability': 'Ketersediaan', 'contact.name': 'Nama Anda', 'contact.emailAddress': 'Alamat Emel', 'contact.service': 'Perkhidmatan', 'contact.selectService': 'Pilih Perkhidmatan', 'contact.detail': 'Butiran Projek', 'contact.detailPlaceholder': 'Ceritakan tentang projek anda…', 'contact.send': 'Hantar Mesej', 'contact.invalid': 'Sila lengkapkan nama dan alamat emel yang sah.', 'contact.failed': 'Mesej tidak dapat dihantar. Sila cuba lagi.', 'contact.thanks': 'Terima kasih. Mesej anda telah diterima.',
    'footer.company': 'Syarikat', 'footer.resources': 'Sumber', 'footer.privacy': 'Dasar Privasi', 'footer.terms': 'Terma Perkhidmatan', 'footer.about': 'Tentang Saya', 'footer.process': 'Proses Saya', 'footer.case': 'Kajian Kes', 'footer.testimonials': 'Testimoni', 'footer.pricing': 'Harga', 'footer.blog': 'Blog & Pandangan', 'footer.guides': 'Panduan', 'footer.changelog': 'Log Perubahan', 'footer.rights': 'Hak cipta terpelihara.',
  },
};

/* Terjemahan untuk konten bawaan/seed yang memang ikut dikirim API. Konten
 * baru dari admin tetap ditampilkan apa adanya sampai pemilik mengisinya dalam
 * bahasa yang diinginkan; nama produk, teknologi, dan company sengaja tidak
 * diterjemahkan karena merupakan nama diri. */
const CONTENT_COPY = {
  id: {
    'Full-Stack Developer & Digital Problem Solver': 'Pengembang Full-Stack & Pemecah Masalah Digital',
    'Engineering Ideas Into Premium Digital Products.': 'Mengubah Ide Menjadi Produk Digital Premium.',
    'I design and build modern websites, SaaS products, and dashboards that are fast, secure, scalable, and crafted for real business impact.': 'Saya merancang dan membangun website modern, produk SaaS, dan dashboard yang cepat, aman, skalabel, serta dibuat untuk dampak bisnis nyata.',
    'Trusted by amazing companies': 'Dipercaya oleh perusahaan hebat',
    "Let's Work Together": 'Mari Bekerja Sama', 'View My Work': 'Lihat Karya Saya', 'Building premium digital solutions that make an impact. Fast, secure, and scalable.': 'Membangun solusi digital premium yang berdampak. Cepat, aman, dan skalabel.', 'Mon – Fri, 09:00 – 18:00 WIB': 'Sen – Jum, 09.00 – 18.00 WIB',
    'Web Development': 'Pengembangan Web', 'SaaS & Web Apps': 'SaaS & Aplikasi Web', 'API Development': 'Pengembangan API', 'UI/UX Design': 'Desain UI/UX', 'Admin Dashboards': 'Dashboard Admin', 'E-Commerce': 'E-Commerce', 'Maintenance & Support': 'Pemeliharaan & Dukungan', 'AI Solutions': 'Solusi AI', 'Modern, responsive websites built with the latest tech.': 'Website modern dan responsif dengan teknologi terbaru.',
    'Scalable applications that solve real business problems.': 'Aplikasi skalabel untuk menyelesaikan masalah bisnis nyata.', 'Robust, secure RESTful APIs and integrations.': 'REST API dan integrasi yang tangguh serta aman.', 'Beautiful, intuitive designs that deliver great experiences.': 'Desain indah dan intuitif untuk pengalaman yang berkesan.', 'Powerful dashboards with beautiful and intuitive UI/UX.': 'Dashboard bertenaga dengan UI/UX indah dan intuitif.', 'High-converting online stores with seamless experience.': 'Toko online berkonversi tinggi dengan pengalaman mulus.', 'Ongoing support and improvements for your apps.': 'Dukungan dan peningkatan berkelanjutan untuk aplikasi Anda.', 'Smart automation and AI integrations for growth.': 'Otomasi cerdas dan integrasi AI untuk pertumbuhan.',
    'Perfect for small projects': 'Cocok untuk proyek kecil', 'Best for growing businesses': 'Terbaik untuk bisnis yang berkembang', 'For advanced solutions': 'Untuk solusi tingkat lanjut', 'Up to 5 Pages': 'Hingga 5 Halaman', 'Responsive Design': 'Desain Responsif', 'Basic SEO': 'SEO Dasar', 'Up to 10 Pages': 'Hingga 10 Halaman', 'CMS Integration': 'Integrasi CMS', 'SEO Optimization': 'Optimasi SEO', '3 Revisions': '3 Revisi', 'Custom Features': 'Fitur Kustom', 'Priority Support': 'Dukungan Prioritas', 'Unlimited Revisions': 'Revisi Tanpa Batas', 'Get Started': 'Mulai Sekarang', 'Contact Us': 'Hubungi Kami',
    'Analytics dashboard for financial management.': 'Dashboard analitik untuk pengelolaan keuangan.', 'Modern educational platform with course management.': 'Platform pendidikan modern dengan pengelolaan kursus.', 'Project management app with Kanban board.': 'Aplikasi manajemen proyek dengan papan Kanban.', 'E-commerce platform with payment integration.': 'Platform e-commerce dengan integrasi pembayaran.', 'Dashboard': 'Dashboard', 'E-Learning': 'Pembelajaran Digital', 'Task Management': 'Manajemen Tugas', 'Productivity': 'Produktivitas', 'Development': 'Pengembangan',
    'What services do you offer?': 'Layanan apa yang Anda tawarkan?', 'I build websites, SaaS products, APIs, dashboards, e-commerce systems, and tailored digital experiences.': 'Saya membangun website, produk SaaS, API, dashboard, sistem e-commerce, dan pengalaman digital yang disesuaikan.', 'How long does a project take?': 'Berapa lama waktu yang dibutuhkan sebuah proyek?', 'A focused website commonly takes 2–6 weeks. Larger applications are planned in clear, reviewable milestones.': 'Website terarah biasanya membutuhkan 2–6 minggu. Aplikasi besar direncanakan dalam milestone yang jelas dan dapat ditinjau.', 'Do you provide ongoing support?': 'Apakah Anda menyediakan dukungan berkelanjutan?', 'Yes. Maintenance, monitoring, improvements, and technical support can continue after launch.': 'Ya. Pemeliharaan, pemantauan, peningkatan, dan dukungan teknis dapat berlanjut setelah peluncuran.', 'What technologies do you use?': 'Teknologi apa yang Anda gunakan?', 'The stack is selected for the product, commonly React, Next.js, Node.js, TypeScript, PostgreSQL, and Docker.': 'Stack dipilih sesuai produk, umumnya React, Next.js, Node.js, TypeScript, PostgreSQL, dan Docker.', 'How do we get started?': 'Bagaimana cara memulainya?', 'Share the outcome you need, your timeline, and current constraints through the project brief below.': 'Bagikan hasil yang dibutuhkan, jadwal, dan kendala saat ini melalui brief proyek di bawah.',
    'PA DEV Studio delivered an outstanding product with great attention to detail. Highly recommended!': 'PA DEV Studio menghadirkan produk luar biasa dengan perhatian tinggi pada detail. Sangat direkomendasikan!', 'Product Manager': 'Manajer Produk',
  },
  ms: {
    'Full-Stack Developer & Digital Problem Solver': 'Pembangun Full-Stack & Penyelesai Masalah Digital', 'Engineering Ideas Into Premium Digital Products.': 'Menukar Idea Menjadi Produk Digital Premium.', 'I design and build modern websites, SaaS products, and dashboards that are fast, secure, scalable, and crafted for real business impact.': 'Saya mereka bentuk dan membina laman web moden, produk SaaS dan papan pemuka yang pantas, selamat, boleh skala serta memberi impak perniagaan sebenar.', 'Trusted by amazing companies': 'Dipercayai oleh syarikat hebat',
    "Let's Work Together": 'Mari Bekerjasama', 'View My Work': 'Lihat Hasil Kerja Saya', 'Building premium digital solutions that make an impact. Fast, secure, and scalable.': 'Membina penyelesaian digital premium yang memberi impak. Pantas, selamat dan boleh skala.', 'Mon – Fri, 09:00 – 18:00 WIB': 'Isn – Jum, 09:00 – 18:00 WIB',
    'Web Development': 'Pembangunan Web', 'SaaS & Web Apps': 'SaaS & Aplikasi Web', 'API Development': 'Pembangunan API', 'UI/UX Design': 'Reka Bentuk UI/UX', 'Admin Dashboards': 'Papan Pemuka Admin', 'E-Commerce': 'E-Dagang', 'Maintenance & Support': 'Penyelenggaraan & Sokongan', 'AI Solutions': 'Penyelesaian AI', 'Modern, responsive websites built with the latest tech.': 'Laman web moden dan responsif dengan teknologi terkini.', 'Scalable applications that solve real business problems.': 'Aplikasi boleh skala yang menyelesaikan masalah perniagaan sebenar.', 'Robust, secure RESTful APIs and integrations.': 'API RESTful dan integrasi yang kukuh serta selamat.', 'Beautiful, intuitive designs that deliver great experiences.': 'Reka bentuk cantik dan intuitif untuk pengalaman hebat.', 'Powerful dashboards with beautiful and intuitive UI/UX.': 'Papan pemuka berkuasa dengan UI/UX yang cantik dan intuitif.', 'High-converting online stores with seamless experience.': 'Kedai dalam talian berkonversi tinggi dengan pengalaman lancar.', 'Ongoing support and improvements for your apps.': 'Sokongan dan penambahbaikan berterusan untuk aplikasi anda.', 'Smart automation and AI integrations for growth.': 'Automasi pintar dan integrasi AI untuk pertumbuhan.',
    'Perfect for small projects': 'Sesuai untuk projek kecil', 'Best for growing businesses': 'Terbaik untuk perniagaan berkembang', 'For advanced solutions': 'Untuk penyelesaian lanjutan', 'Up to 5 Pages': 'Sehingga 5 Halaman', 'Responsive Design': 'Reka Bentuk Responsif', 'Basic SEO': 'SEO Asas', 'Up to 10 Pages': 'Sehingga 10 Halaman', 'CMS Integration': 'Integrasi CMS', 'SEO Optimization': 'Pengoptimuman SEO', '3 Revisions': '3 Semakan', 'Custom Features': 'Ciri Tersuai', 'Priority Support': 'Sokongan Keutamaan', 'Unlimited Revisions': 'Semakan Tanpa Had', 'Get Started': 'Mulakan', 'Contact Us': 'Hubungi Kami',
    'Analytics dashboard for financial management.': 'Papan pemuka analitik untuk pengurusan kewangan.', 'Modern educational platform with course management.': 'Platform pendidikan moden dengan pengurusan kursus.', 'Project management app with Kanban board.': 'Aplikasi pengurusan projek dengan papan Kanban.', 'E-commerce platform with payment integration.': 'Platform e-dagang dengan integrasi pembayaran.', 'Dashboard': 'Papan Pemuka', 'E-Learning': 'Pembelajaran Digital', 'Task Management': 'Pengurusan Tugas', 'Productivity': 'Produktiviti', 'Development': 'Pembangunan',
    'What services do you offer?': 'Apakah perkhidmatan yang anda tawarkan?', 'I build websites, SaaS products, APIs, dashboards, e-commerce systems, and tailored digital experiences.': 'Saya membina laman web, produk SaaS, API, papan pemuka, sistem e-dagang dan pengalaman digital tersuai.', 'How long does a project take?': 'Berapa lama projek mengambil masa?', 'A focused website commonly takes 2–6 weeks. Larger applications are planned in clear, reviewable milestones.': 'Laman web berfokus biasanya mengambil masa 2–6 minggu. Aplikasi besar dirancang dalam pencapaian yang jelas dan boleh disemak.', 'Do you provide ongoing support?': 'Adakah anda menyediakan sokongan berterusan?', 'Yes. Maintenance, monitoring, improvements, and technical support can continue after launch.': 'Ya. Penyelenggaraan, pemantauan, penambahbaikan dan sokongan teknikal boleh diteruskan selepas pelancaran.', 'What technologies do you use?': 'Apakah teknologi yang anda gunakan?', 'The stack is selected for the product, commonly React, Next.js, Node.js, TypeScript, PostgreSQL, and Docker.': 'Stack dipilih mengikut produk, lazimnya React, Next.js, Node.js, TypeScript, PostgreSQL dan Docker.', 'How do we get started?': 'Bagaimana untuk bermula?', 'Share the outcome you need, your timeline, and current constraints through the project brief below.': 'Kongsi hasil yang diperlukan, garis masa dan kekangan semasa melalui ringkasan projek di bawah.',
    'PA DEV Studio delivered an outstanding product with great attention to detail. Highly recommended!': 'PA DEV Studio menyampaikan produk cemerlang dengan perhatian terperinci. Sangat disyorkan!', 'Product Manager': 'Pengurus Produk',
  },
};

const terjemahkan = (value, locale) => CONTENT_COPY[locale]?.[value] || value;
const formatDate = (value, locale) => {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(locale === 'id' ? 'id-ID' : 'ms-MY', { month: 'long', day: 'numeric', year: 'numeric' }).format(date);
};

export const translateContent = (content, locale) => {
  if (locale === 'en') return content;
  const map = (item, fields) => Object.fromEntries(Object.entries(item).map(([key, value]) => [
    key,
    fields.includes(key) && typeof value === 'string' ? terjemahkan(value, locale)
      : fields.includes(key) && Array.isArray(value) ? value.map((entry) => terjemahkan(entry, locale))
        : value,
  ]));
  return {
    ...content,
    capabilities: content.capabilities.map((item) => map(item, ['title', 'text'])),
    plans: content.plans.map((item) => map(item, ['desc', 'features', 'cta'])),
    projects: content.projects.map((item) => map(item, ['text'])),
    insights: content.insights.map((item) => ({ ...map(item, ['category', 'title']), date: formatDate(item.date, locale) })),
    faqs: content.faqs.map((item) => map(item, ['question', 'answer'])),
    testimonials: content.testimonials.map((item) => map(item, ['quote', 'role'])),
    homepage: map(content.homepage, ['hero_eyebrow', 'hero_title', 'hero_subtitle', 'trust_note', 'cta_primary_label', 'cta_secondary_label']),
    settings: map(content.settings, ['site_tagline', 'contact_availability']),
  };
};

const I18nContext = createContext({ locale: 'en', setLocale: () => {}, t: (key) => key });

export function I18nProvider({ children }) {
  const [locale, setLocaleState] = useState(() => {
    const saved = window.localStorage.getItem('padev-language');
    return COPY[saved] ? saved : 'en';
  });
  const setLocale = (next) => {
    const value = COPY[next] ? next : 'en';
    setLocaleState(value);
    window.localStorage.setItem('padev-language', value);
    document.documentElement.lang = value;
  };
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (key) => COPY[locale][key] || COPY.en[key] || key }), [locale]);
  return createElement(I18nContext.Provider, { value }, children);
}

export const useI18n = () => useContext(I18nContext);
